import { Task, TaskStatus, TaskPriority } from "./app/applications/creative/deadline/types"

export const mockTasks: Task[] = [
  {
    id: "task-001",
    briefId: "brief-01",
    title: "Design Banner for Summer Campaign",
    type: "asset",
    status: "in_progress",
    priority: "high",
    assignedTo: ["user-01", "user-02"],
    assignedBy: "user-10",
    createdAt: "2024-06-01T09:00:00Z",
    deadline: "2024-06-10T17:00:00Z",
    startDate: "2024-06-02T09:00:00Z",
    appName: "Brief & Task Management",
    campaignName: "Summer Campaign",
    description: "Main banner for UA channels",
    progress: 60,
    estimatedHours: 12,
    actualHours: 7,
  },
  {
    id: "task-002",
    briefId: "brief-01",
    title: "Concept Brainstorm: Summer Slogan",
    type: "concept",
    status: "pending",
    priority: "medium",
    assignedTo: ["user-03"],
    assignedBy: "user-10",
    createdAt: "2024-06-03T10:00:00Z",
    deadline: "2024-06-08T12:00:00Z",
    appName: "Concept & Idea Hub",
    campaignName: "Summer Campaign",
    description: "Brainstorm catchy slogans",
    progress: 0,
    estimatedHours: 4,
  },
  {
    id: "task-003",
    briefId: "brief-02",
    title: "Review Video Asset",
    type: "review",
    status: "review",
    priority: "urgent",
    assignedTo: ["user-04"],
    assignedBy: "user-11",
    createdAt: "2024-06-04T11:00:00Z",
    deadline: "2024-06-06T15:00:00Z",
    appName: "Asset Management",
    campaignName: "Video Launch",
    description: "Review final cut",
    progress: 80,
    estimatedHours: 2,
    actualHours: 1.5,
  },
  {
    id: "task-004",
    briefId: "brief-03",
    title: "Prepare Creative Brief for Q3",
    type: "brief",
    status: "completed",
    priority: "high",
    assignedTo: ["user-05"],
    assignedBy: "user-12",
    createdAt: "2024-05-28T08:00:00Z",
    deadline: "2024-06-02T17:00:00Z",
    startDate: "2024-05-29T09:00:00Z",
    completedAt: "2024-06-01T16:00:00Z",
    appName: "Brief & Task Management",
    description: "Brief for Q3 creative direction",
    progress: 100,
    estimatedHours: 6,
    actualHours: 5.5,
  },
  {
    id: "task-005",
    briefId: "brief-04",
    title: "Update Asset Library",
    type: "asset",
    status: "overdue",
    priority: "urgent",
    assignedTo: ["user-02"],
    assignedBy: "user-10",
    createdAt: "2024-05-25T09:00:00Z",
    deadline: "2024-06-01T17:00:00Z",
    appName: "Asset Management",
    description: "Add new assets for July",
    progress: 40,
    estimatedHours: 8,
    actualHours: 3,
  },
  {
    id: "task-006",
    briefId: "brief-05",
    title: "Feedback on Banner Design",
    type: "review",
    status: "pending",
    priority: "low",
    assignedTo: ["user-06"],
    assignedBy: "user-01",
    createdAt: "2024-06-05T12:00:00Z",
    deadline: "2024-06-12T17:00:00Z",
    appName: "Brief & Task Management",
    description: "Provide feedback for banner",
    progress: 0,
    estimatedHours: 1,
  },
  {
    id: "task-007",
    briefId: "brief-06",
    title: "Asset Approval: Social Media",
    type: "review",
    status: "in_progress",
    priority: "medium",
    assignedTo: ["user-07"],
    assignedBy: "user-02",
    createdAt: "2024-06-06T13:00:00Z",
    deadline: "2024-06-09T17:00:00Z",
    appName: "Asset Management",
    description: "Approve assets for social posts",
    progress: 30,
    estimatedHours: 3,
    actualHours: 1,
  },
  {
    id: "task-008",
    briefId: "brief-07",
    title: "Design Concept: Autumn Theme",
    type: "concept",
    status: "pending",
    priority: "low",
    assignedTo: ["user-08"],
    assignedBy: "user-10",
    createdAt: "2024-06-07T14:00:00Z",
    deadline: "2024-06-20T17:00:00Z",
    appName: "Concept & Idea Hub",
    description: "Initial concept for autumn",
    progress: 0,
    estimatedHours: 5,
  },
  {
    id: "task-009",
    briefId: "brief-08",
    title: "Finalize Asset for UA",
    type: "asset",
    status: "completed",
    priority: "high",
    assignedTo: ["user-09"],
    assignedBy: "user-03",
    createdAt: "2024-06-01T09:00:00Z",
    deadline: "2024-06-05T17:00:00Z",
    startDate: "2024-06-02T09:00:00Z",
    completedAt: "2024-06-04T16:00:00Z",
    appName: "Asset Management",
    campaignName: "UA Push",
    description: "Finalize asset for UA push",
    progress: 100,
    estimatedHours: 7,
    actualHours: 6.5,
  },
  {
    id: "task-010",
    briefId: "brief-09",
    title: "Brief: New Product Launch",
    type: "brief",
    status: "in_progress",
    priority: "urgent",
    assignedTo: ["user-10", "user-11"],
    assignedBy: "user-12",
    createdAt: "2024-06-08T09:00:00Z",
    deadline: "2024-06-15T17:00:00Z",
    appName: "Brief & Task Management",
    campaignName: "Product Launch",
    description: "Prepare launch brief",
    progress: 20,
    estimatedHours: 10,
    actualHours: 2,
  },
  {
    id: "task-011",
    briefId: "brief-10",
    title: "Asset: Email Header Design",
    type: "asset",
    status: "pending",
    priority: "medium",
    assignedTo: ["user-12"],
    assignedBy: "user-01",
    createdAt: "2024-06-09T10:00:00Z",
    deadline: "2024-06-13T17:00:00Z",
    appName: "Asset Management",
    description: "Design header for email blast",
    progress: 0,
    estimatedHours: 2,
  },
  {
    id: "task-012",
    briefId: "brief-11",
    title: "Review: Social Ad Copy",
    type: "review",
    status: "review",
    priority: "high",
    assignedTo: ["user-01"],
    assignedBy: "user-03",
    createdAt: "2024-06-10T11:00:00Z",
    deadline: "2024-06-12T17:00:00Z",
    appName: "Brief & Task Management",
    description: "Review ad copy for social",
    progress: 50,
    estimatedHours: 1,
    actualHours: 0.5,
  },
  {
    id: "task-013",
    briefId: "brief-12",
    title: "Concept: Winter Campaign",
    type: "concept",
    status: "pending",
    priority: "medium",
    assignedTo: ["user-02"],
    assignedBy: "user-10",
    createdAt: "2024-06-11T12:00:00Z",
    deadline: "2024-06-25T17:00:00Z",
    appName: "Concept & Idea Hub",
    campaignName: "Winter Campaign",
    description: "Brainstorm winter ideas",
    progress: 0,
    estimatedHours: 6,
  },
  {
    id: "task-014",
    briefId: "brief-13",
    title: "Asset: Instagram Story",
    type: "asset",
    status: "in_progress",
    priority: "high",
    assignedTo: ["user-03"],
    assignedBy: "user-01",
    createdAt: "2024-06-12T13:00:00Z",
    deadline: "2024-06-18T17:00:00Z",
    appName: "Asset Management",
    description: "Design IG story asset",
    progress: 40,
    estimatedHours: 3,
    actualHours: 1,
  },
  {
    id: "task-015",
    briefId: "brief-14",
    title: "Brief: Influencer Collaboration",
    type: "brief",
    status: "pending",
    priority: "low",
    assignedTo: ["user-04"],
    assignedBy: "user-12",
    createdAt: "2024-06-13T14:00:00Z",
    deadline: "2024-06-20T17:00:00Z",
    appName: "Brief & Task Management",
    campaignName: "Influencer Collab",
    description: "Prepare brief for influencer",
    progress: 0,
    estimatedHours: 5,
  },
  {
    id: "task-016",
    briefId: "brief-15",
    title: "Review: Asset for Facebook Ads",
    type: "review",
    status: "completed",
    priority: "medium",
    assignedTo: ["user-05"],
    assignedBy: "user-03",
    createdAt: "2024-06-14T15:00:00Z",
    deadline: "2024-06-16T17:00:00Z",
    startDate: "2024-06-15T09:00:00Z",
    completedAt: "2024-06-16T16:00:00Z",
    appName: "Asset Management",
    description: "Review FB ad asset",
    progress: 100,
    estimatedHours: 2,
    actualHours: 2,
  },
  {
    id: "task-017",
    briefId: "brief-16",
    title: "Asset: Landing Page Graphics",
    type: "asset",
    status: "overdue",
    priority: "urgent",
    assignedTo: ["user-06"],
    assignedBy: "user-01",
    createdAt: "2024-06-15T16:00:00Z",
    deadline: "2024-06-17T17:00:00Z",
    appName: "Asset Management",
    description: "Graphics for landing page",
    progress: 10,
    estimatedHours: 4,
    actualHours: 0.5,
  },
  {
    id: "task-018",
    briefId: "brief-17",
    title: "Concept: Spring Refresh",
    type: "concept",
    status: "in_progress",
    priority: "medium",
    assignedTo: ["user-07"],
    assignedBy: "user-10",
    createdAt: "2024-06-16T17:00:00Z",
    deadline: "2024-06-23T17:00:00Z",
    appName: "Concept & Idea Hub",
    campaignName: "Spring Refresh",
    description: "New concept for spring",
    progress: 25,
    estimatedHours: 5,
    actualHours: 1,
  },
  {
    id: "task-019",
    briefId: "brief-18",
    title: "Brief: App Update",
    type: "brief",
    status: "pending",
    priority: "high",
    assignedTo: ["user-08"],
    assignedBy: "user-12",
    createdAt: "2024-06-17T18:00:00Z",
    deadline: "2024-06-22T17:00:00Z",
    appName: "Brief & Task Management",
    campaignName: "App Update",
    description: "Prepare brief for app update",
    progress: 0,
    estimatedHours: 3,
  },
  {
    id: "task-020",
    briefId: "brief-19",
    title: "Review: Asset for TikTok",
    type: "review",
    status: "review",
    priority: "high",
    assignedTo: ["user-09"],
    assignedBy: "user-03",
    createdAt: "2024-06-18T19:00:00Z",
    deadline: "2024-06-21T17:00:00Z",
    appName: "Asset Management",
    description: "Review TikTok asset",
    progress: 70,
    estimatedHours: 2,
    actualHours: 1,
  },
  {
    id: "task-021",
    briefId: "brief-20",
    title: "Asset: Newsletter Graphics",
    type: "asset",
    status: "pending",
    priority: "low",
    assignedTo: ["user-10"],
    assignedBy: "user-01",
    createdAt: "2024-06-19T20:00:00Z",
    deadline: "2024-06-27T17:00:00Z",
    appName: "Asset Management",
    description: "Graphics for newsletter",
    progress: 0,
    estimatedHours: 3,
  },
]
